ARG BASE_IMAGE=mobrob-ros2-ros2:latest
FROM ${BASE_IMAGE}

# 必须使用 root 权限安装软件
USER root

# 更新并在构建时安装基础依赖和自动烧录缺失的 nav2 核心导航库
RUN apt-get update && \
    apt-get install -y git build-essential ros-$ROS_DISTRO-navigation2 ros-$ROS_DISTRO-nav2-core && \
    rm -rf /var/lib/apt/lists/*

# 从源码重新编译安装被时代抛弃的先锋 Aria 底层 C++ 库，并建立全局软链接，防止 Aria/Aria.h 找不到错误！
RUN git clone https://github.com/amor-ros-pkg/libaria.git /tmp/libaria && \
    cd /tmp/libaria && \
    make -j4 && \
    make install && \
    ln -s /usr/local/Aria/include /usr/local/include/Aria && \
    ln -s /usr/local/Aria/lib/libAria.so /usr/lib/libAria.so && \
    rm -rf /tmp/libaria

# 设置默认进来的目录
WORKDIR /workspace
